# This is a basic workflow to help you get started with Actions

name: TestCafe workflow

# Controls when the workflow will run
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Run TestCafe tests
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install TestCafe from npm and Run Tests
    - uses: DevExpress/testcafe-action@latest
      with:
        args: "chrome ./Page_Model_Demo/test/registrationTest.js"
