name: TestCafe workflow
on: [push]

jobs:
  build:
    name: Run TestCafe tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install TestCafe from npm and Run Tests
    - uses: DevExpress/testcafe-action@latest
      with:
        args: "chrome ./Page_Model_Demo/test/registrationTest.js"
